### ISSUE TITLE
Unsatisfied dependency: nim (> 0.13.0)

### ISSUE THREAD

**Issue by enthus1ast** [nim-lang/python#3]
Installing this with nimble gives:

> Unsatisfied dependency: nim (> 0.13.0)

forgot an '=' ?

**Comment by matkuki** [comment]
Thanks for the report.
Created the fix[https://github.com/nim-lang/python/pull/4].
@dom96, please merge!

**Comment by matkuki** [comment]
Thanks Araq!

@enthus1ast, can you try it now, please?

**Comment by enthus1ast** [comment]
jep works!
`python installed successfully`
